In [43]:
import pandas as pd
raw_data = pd.read_csv("part-amazon-reviews-unlocked-mobile-phones.csv") 
raw_data.head()

Unnamed: 0  Rating                                            Reviews
0           0       5  I feel so LUCKY to have found this used (phone...
1           1       4  nice phone, nice up grade from my pantach revu...
2           2       5                                       Very pleased
3           3       4  It works good but it goes slow sometimes but i...
4           4       4  Great phone to replace my lost phone. The only...

In [44]:
raw_corpus = u"".join(raw_data['Reviews']+" ")
print("Raw Corpus contains {0:,} characters".format(len(raw_corpus)))
print(len(raw_data))
print(raw_corpus)

Raw Corpus contains 1,630,916 characters
6000
I feel so LUCKY to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. My Son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! Thank you Seller, we really appreciate it & your honesty re: said used phone.I recommend this seller very highly & would but from them again!! nice phone, nice up grade from my pantach revue. Very clean set up and easy set up. never had an android phone but they are fantastic to say the least. perfect size for surfing and social media. great phone samsung Very pleased It works good but it goes slow sometimes but its a very good phone I love it Great phone to replace my lost phone. The only thing is the volume up button does not work, but I can still go into settings to adjust. Other than that, it does the job until I am eligible to upgrade my phone again.Thaanks! I already had a phone with problems... I know it s

In [45]:
import nltk
nltk.download('punkt')
tokenizer = nltk.data.load("tokenizers/punkt/english.pickle")
raw_sentences = tokenizer.tokenize(raw_corpus)
print("We have {0:,} raw sentences".format(len(raw_sentences)))
print(raw_sentences[0:200])


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\begum\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


We have 18,381 raw sentences
['I feel so LUCKY to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one.', "My Son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!!", 'Thank you Seller, we really appreciate it & your honesty re: said used phone.I recommend this seller very highly & would but from them again!!', 'nice phone, nice up grade from my pantach revue.', 'Very clean set up and easy set up.', 'never had an android phone but they are fantastic to say the least.', 'perfect size for surfing and social media.', 'great phone samsung Very pleased It works good but it goes slow sometimes but its a very good phone I love it Great phone to replace my lost phone.', 'The only thing is the volume up button does not work, but I can still go into settings to adjust.', 'Other than that, it does the job until I am eligible to upgrade my phone again.Thaanks!', 'I already had a phone with problems

In [46]:
#regular expression library
import re
import spacy
from spacy.lang.en import English
from spacy import displacy
nlp = spacy.load('en')
from spacy.tokenizer import Tokenizer
from spacy.lang.en.stop_words import STOP_WORDS
nlp.max_length = 1800000


def clean_data(string):
    strip_special_chars = re.compile("[^A-Za-z]+")
    string = re.sub(strip_special_chars, " ", string)
    return string.strip().split()

raw_corpus = raw_corpus.lower()
#rawtext = re.sub(r"[?!&:;]"," ", rawtext) 

prefix_re = re.compile(r'''^[[(?!.;:,"']''')  # It handles punctuations coming before a word such open quotes, open brackets
suffix_re = re.compile(r'''[])?!.;:,"']$''')  # It handles punctuation coming after a word such as commas, periods, close quotes 
infix_re = re.compile(r'''[-~]''') # It handles non-white spaces such as hyphens


def custom_tokenizer(nlp):
    return Tokenizer(nlp.vocab, prefix_search=prefix_re.search,
                                suffix_search=suffix_re.search,
                                infix_finditer=infix_re.finditer)
                               

nlp.tokenizer = custom_tokenizer(nlp)
document = nlp(raw_corpus)
#document = []
#for raw_sent in raw_sentences:
#    if len(raw_sent) > 0:
#        document.append(clean_data(raw_sent))
document = [token.orth_ for token in document if not token.is_punct | token.is_space] #  It takes care of the spaces put instead of a punctuation
#print(document[0:200])
sentences = []
for sent in document:
    if len(sent) > 0:
        sentences.append(clean_data(sent))
#del raw_sentences
print(sentences[0:2000])
#filtered_sentences =[] 

#for word in document:
#    lexeme = nlp.vocab[word]
#    if lexeme.is_stop == False:
 #       filtered_sentences.append(word) 
#print(document[0:200])
#print(filtered_sentences[0:200]) 


[['i'], ['feel'], ['so'], ['lucky'], ['to'], ['have'], ['found'], ['this'], ['used'], ['phone'], ['to'], ['us'], ['not'], ['used'], ['hard'], ['at'], ['all'], ['phone'], ['on'], ['line'], ['from'], ['someone'], ['who'], ['upgraded'], ['and'], ['sold'], ['this'], ['one'], ['my'], ['son'], ['liked'], ['his'], ['old'], ['one'], ['that'], ['finally'], ['fell'], ['apart'], ['after'], [], ['years'], ['and'], ['didn', 't'], ['want'], ['an'], ['upgrade'], ['thank'], ['you'], ['seller'], ['we'], ['really'], ['appreciate'], ['it'], ['your'], ['honesty'], ['re'], ['said'], ['used'], ['phone', 'i'], ['recommend'], ['this'], ['seller'], ['very'], ['highly'], ['would'], ['but'], ['from'], ['them'], ['again'], ['nice'], ['phone'], ['nice'], ['up'], ['grade'], ['from'], ['my'], ['pantach'], ['revue'], ['very'], ['clean'], ['set'], ['up'], ['and'], ['easy'], ['set'], ['up'], ['never'], ['had'], ['an'], ['android'], ['phone'], ['but'], ['they'], ['are'], ['fantastic'], ['to'], ['say'], ['the'], ['least'

In [25]:
import itertools

words = set(itertools.chain(*filtered_sentences[0:1000]))
print(words)
vocab_size = len(words)
print(vocab_size)
word2int = {}
int2word = {}

for i,word in enumerate(words):
    word2int[word] = i
    int2word[i] = word

del words
filtered_sentences = filtered_sentences[0:1000]
#print("word2int", word2int)
#print("int2word", int2word)

{'RECOMIENDO', 'do', 'occasionally', 'weeks', 'presses', 'advanced', 'grandfather', 'protector', 'walk', 'year', 'certain', 'get', 'Flip', 'Would', 'guide', 'American', 'bad', 'lower', 'locking', 'selection', 'ram', 'except', 'forgot', 'leather', 'Like', 'warranty', 'micro', 'Sometimes', 'cant', 'simple', 'theirs', 'SPAM', 'keys', 'pros', 'INCORPORATED', 'prefers', 'word', 'embrace', 'track', 'averaging', 'If', 'particular', 'Whatever', 'important', 'bands', 'upgrade', 'items', 'put', 'Needed', 'risky', 'proved', 'easier', 'product', 'cm', 'visiting', 'core', 'prepaid', 'Daughter', 'above', 'Dec', 'qwerty', 'Sound', 'box', 'arm', 'otro', 'Unlocked', 'same', 'messes', 'whatsapp', 'may', 'print', 'Isn', 'hands', 'enjoying', 'slow', 'America', 'dumping', 'interference', 'addressed', 'trying', 'gb', 'useless', 'employee', 'speakers', 'DAILY', 'seas', 'APPS', 'cats', 'correct', 'keeps', 'EDIT', 'THEM', 'label', 'con', 'menu', 'Exactly', 'db', 'Fast', 'IPS', 'Tegra', 'has', 'pickings', 'sent

In [26]:
import numpy as np
window_size = 1
data = []
print(word2int)
for sentence in document:         # Look for each sentence in the document
    #print("I'm the sentence", sentence)
    for word_index, word, in enumerate(sentence):
        for nb_word in sentence[max(word_index - window_size, 0): 
                            min(word_index + window_size, len(sentence)) + 1]:
            #print("I'm the nb_word:", nb_word)
            if nb_word != word:
                data.append([word2int[str(word)], word2int[str(nb_word)]])

data = np.asarray(data)
print(data)
#print(int2word[data[2, 0]], int2word[data[2, 1]])

print(len(data))

{'RECOMIENDO': 0, 'do': 1, 'occasionally': 2, 'weeks': 3, 'presses': 4, 'advanced': 5, 'grandfather': 6, 'protector': 7, 'walk': 8, 'year': 9, 'certain': 10, 'get': 11, 'Flip': 12, 'Would': 13, 'guide': 14, 'American': 15, 'bad': 16, 'lower': 17, 'locking': 18, 'selection': 19, 'ram': 20, 'except': 21, 'forgot': 22, 'leather': 23, 'Like': 24, 'warranty': 25, 'micro': 26, 'Sometimes': 27, 'cant': 28, 'simple': 29, 'theirs': 30, 'SPAM': 31, 'keys': 32, 'pros': 33, 'INCORPORATED': 34, 'prefers': 35, 'word': 36, 'embrace': 37, 'track': 38, 'averaging': 39, 'If': 40, 'particular': 41, 'Whatever': 42, 'important': 43, 'bands': 44, 'upgrade': 45, 'items': 46, 'put': 47, 'Needed': 48, 'risky': 49, 'proved': 50, 'easier': 51, 'product': 52, 'cm': 53, 'visiting': 54, 'core': 55, 'prepaid': 56, 'Daughter': 57, 'above': 58, 'Dec': 59, 'qwerty': 60, 'Sound': 61, 'box': 62, 'arm': 63, 'otro': 64, 'Unlocked': 65, 'same': 66, 'messes': 67, 'whatsapp': 68, 'may': 69, 'print': 70, 'Isn': 71, 'hands': 72

In [16]:
def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp

x_train = np.zeros((len(data[:, 0]), vocab_size)) # input word
y_train = np.zeros((len(data[:, 0]), vocab_size)) # output word
i = -1
for data_word1, data_word2 in data:
    i += 1
    x_train[i, :] = (to_one_hot(data_word1, vocab_size))
    y_train[i, :] = (to_one_hot(data_word2, vocab_size))
del data
# convert them to numpy arrays
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)
print("xtrain", x_train,len(x_train),x_train[0][399])  #np.where(x_train==1) 2D tuple where the first one is row and second one is column
print("ytrain", y_train,len(y_train))

xtrain [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 29212 0.0
ytrain [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 29212


In [27]:
# build vocabulary and train model
import gensim
model = gensim.models.Word2Vec(
    document,
    size=150,
    window=5,
    min_count=2,
    workers=10)
model.train(document, total_examples=len(document), epochs=50)
model.save("word2vec.model")
#w1 = ["perfect"]
w1 = ["good"]
model.wv.most_similar(positive=w1,topn=10)


[('quality', 0.9484284520149231),
 ('feature', 0.9474878311157227),
 ('very', 0.944629967212677),
 ('flashlight', 0.9407147765159607),
 ('Phone', 0.9238414764404297),
 ('slow', 0.9098459482192993),
 ('build', 0.9094902276992798),
 ('small', 0.9092936515808105),
 ('life', 0.9060045480728149),
 ('nice', 0.9046250581741333)]

In [28]:
w2 = ["bad"]
model.wv.most_similar(negative=w2,topn=10)

[('card', -0.27044662833213806),
 ('t', -0.3374137580394745),
 ('to', -0.34348684549331665),
 ('do', -0.3460460305213928),
 ('don', -0.34781473875045776),
 ('want', -0.35025396943092346),
 ('T', -0.3513636589050293),
 ('if', -0.3529226779937744),
 ('get', -0.35296595096588135),
 ('would', -0.3535364270210266)]